config:
    tailscale:
        env: ENC[AES256_GCM,data:QxzU5WbU+xu0QBYfOa8qfvhktanOzNLOGMTDTCh+eZ8S11Thyj9giqlRGWngAelSUzFFlFsD9NSZ6gYW/sZH1ABXI78mgOb5icJSn8U47NrODXFYuet/fB8YnlyHYfeDT79aALTypY/5pW4T+R67MPe7fQdsyI2rzCqKmdt/8Sokb9693onO/5W467M9CX2fKUW96nAvaKJ/JUz/L2GwxtzWJbLpdU409OzJvV1fhm+GJYlIp5yDL9G03ycwe50jx7dqYKuRW9/i24PfTFs6rgx4Nnzp,iv:HXhP01uPGEQHS5puiZmwhjOftaD0NURIjyGRGxPoKCg=,tag:0cmnIQ5QcIpU9NXdCHSLTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-25T06:25:29Z"
    mac: ENC[AES256_GCM,data:K1yhN+b4YDVzwYkpns+/npD/UBFf8cnh6uEApRAgNpC5WiMXsYUUHJncaYvxhz51iuT4DFdTnyjwH6FUIZCO+0ggJ0j9Og3PwW7poV46FySvikrH9H7X2FRjLmu+LIThYiw9RTN52f6T5bmaTGG17Dya5wi/IOWKeYAnowwXWHM=,iv:2TPjauaK3O99IeF5UO9xiBurX0KtiDMB/Gc888AUUW0=,tag:9QKvcTF92Qc6+VucR+OHIg==,type:str]
    pgp:
        - created_at: "2024-12-25T04:42:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DHu6f5NSYqbsSAQdA2DgXycmJzSLUO7DZwZoCMBKWNZpwdTGIY/o62x4tM2sw
            X9iZlHX79qJuwb5R6GyLA/1GSe0ZBO5oDEUP64w44AABFc0+p6VP0zoyJ6BaBcKh
            1GYBCQIQvm020NcnveDYjCcQvrt3dvNqCLYIIQxJWe/p2vdWPpQ3r3pDAYCaKncz
            n+Z6NqVS4aPzJeiBWpqpnWQo3WSO/YXcUijRv2fZ9zSeY8qaco/SLcBPdGePb7BD
            gm4l42OuGCI=
            =zIEF
            -----END PGP MESSAGE-----
          fp: 895490CB812A62406B00D6517AB5E4BB6A8E3568
    unencrypted_suffix: _unencrypted
    version: 3.8.1
