volumes:
  gomod: {}
  gocache: {}
  tzdb-vol: {}
services:
  summarizer-server:
    build:
      context: .
    environment:
      - SERVER_HOST
      - SERVER_PORT
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
    command:
      - serve
  build:
    image: golang:${GOLANG_VERSION}-alpine
    volumes:
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
      - $PWD/out:/out
      - $PWD:/usr/local/go/src/project
    working_dir: /usr/local/go/src/project
    entrypoint: [ "sh" ]
    environment:
      - CGO_ENABLED=0
      - GOOS=${GOOS:-linux}
      - GOARCH=${GOARCH:-arm64}
      - PROJECT_NAME
    command:
      - -c
      - |
        go build -o "/out/${PROJECT_NAME}-$${GOOS}-$${GOARCH}" ./cmd/${PROJECT_NAME}/main.go
  test:
    image: golang:${GOLANG_VERSION}-alpine
    volumes:
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
      - $PWD:/usr/local/go/src/project
    working_dir: /usr/local/go/src/project
    entrypoint: [ "go" ]
    environment:
      - TEST_EXCLUDE
      - TEST_FILTER
      - CGO_ENABLED=0
      - GOOS=${GOOS:-linux}
      - GOARCH=${GOARCH:-arm64}
    command:
      - test
      - -failfast
      - ./...
      - -skip
      - ${TEST_EXCLUDE:-E2E}
      - -run
      - ${TEST_FILTER:-.*}
  e2e:
    depends_on:
      retrieve_timezones:
        condition: service_completed_successfully
    image: golang:${GOLANG_VERSION}-alpine
    volumes:
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
      - tzdb-vol:/data
      - $PWD:/usr/local/go/src/project
    working_dir: /usr/local/go/src/project
    entrypoint: [ "go" ]
    environment:
      - TEST_EXCLUDE
      - TEST_FILTER
      - CGO_ENABLED=0
      - GOOS=${GOOS:-linux}
      - GOARCH=${GOARCH:-arm64}
    command:
      - test
      - -failfast
      - ./...
      - -run
      - E2E
  retrieve_timezones:
    image: curlimages/curl:8.11.1
    entrypoint: sh
    user: root
    environment:
      - REFRESH_TZ
    volumes:
      - tzdb-vol:/out
      - $PWD/include/refresh_tz.sh:/script.sh
    command:
      - /script.sh
