volumes:
  gomod: {}
  gocache: {}
  tzdb-vol: {}
services:
  summarizer-server:
    build:
      context: .
    environment:
      - SERVER_HOST
      - SERVER_PORT
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
    command:
      - serve
  deploy-to-ghcr:
    image: docker:27.4.1-cli-alpine3.21
    volumes:
      - $PWD/Dockerfile:/work/Dockerfile
      - $PWD/out:/work/out
      - $PWD/include:/work/include
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /work
    environment:
      - GITHUB_REPOSITORY
      - GITHUB_TOKEN
      - PROJECT_NAME
      - ARCHITECTURES_CSV
      - BUILD_TAGS
    entrypoint: [ "sh" ]
    command:
      - -c
      - |
        set -eo pipefail
        docker buildx ls | grep -q "${PROJECT_NAME}-builder" ||
          docker buildx create --driver docker-container \
            --name "${PROJECT_NAME}-builder" &>/dev/null
        docker login ghcr.io -u "$(echo "$GITHUB_REPOSITORY" | cut -f1 -d '/')" -p "$GITHUB_TOKEN"
        >&2 echo "INFO: Building $PROJECT_NAME for archs: $ARCHITECTURES_CSV"
        for tag in $(echo "$BUILD_TAGS" | tr ',' ' ')
        do
          this_tag="ghcr.io/$GITHUB_REPOSITORY:$$tag"
          docker buildx build --builder "${PROJECT_NAME}-builder" \
            -t "$$this_tag" \
            --build-arg PROJECT_NAME="$PROJECT_NAME" \
            --platform "$ARCHITECTURES_CSV" \
            --output registry \
            --push \
            .
        done
  build:
    image: golang:${GOLANG_VERSION}-alpine
    volumes:
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
      - $PWD/out:/out
      - $PWD:/usr/local/go/src/project
    working_dir: /usr/local/go/src/project
    entrypoint: [ "sh" ]
    environment:
      - CGO_ENABLED=0
      - GOOS=${GOOS:-linux}
      - GOARCH=${GOARCH:-arm64}
      - PROJECT_NAME
    command:
      - -c
      - |
        go build -o "/out/${PROJECT_NAME}-$${GOOS}-$${GOARCH}" ./cmd/${PROJECT_NAME}/main.go
  test:
    image: golang:${GOLANG_VERSION}-alpine
    volumes:
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
      - $PWD:/usr/local/go/src/project
    working_dir: /usr/local/go/src/project
    entrypoint: [ "go" ]
    environment:
      - TEST_EXCLUDE
      - TEST_FILTER
      - CGO_ENABLED=0
      - GOOS=${GOOS:-linux}
      - GOARCH=${GOARCH:-arm64}
    command:
      - test
      - -failfast
      - ./...
      - -skip
      - ${TEST_EXCLUDE:-E2E}
      - -run
      - ${TEST_FILTER:-.*}
  e2e:
    depends_on:
      retrieve_timezones:
        condition: service_completed_successfully
    image: golang:${GOLANG_VERSION}-alpine
    volumes:
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
      - tzdb-vol:/data
      - $PWD:/usr/local/go/src/project
    working_dir: /usr/local/go/src/project
    entrypoint: [ "go" ]
    environment:
      - TEST_EXCLUDE
      - TEST_FILTER
      - CGO_ENABLED=0
      - GOOS=${GOOS:-linux}
      - GOARCH=${GOARCH:-arm64}
    command:
      - test
      - -failfast
      - ./...
      - -run
      - E2E
  retrieve_timezones:
    image: curlimages/curl:8.11.1
    entrypoint: sh
    user: root
    environment:
      - REFRESH_TZ
    volumes:
      - tzdb-vol:/out
      - $PWD/include/refresh_tz.sh:/script.sh
    command:
      - /script.sh
  _remove_buildx_builder:
    image: docker:27.4.1-cli-alpine3.21
    volumes:
      - $PWD/Dockerfile:/work/Dockerfile
      - $PWD/out:/work/out
      - $PWD/include:/work/include
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /work
    environment:
      - PROJECT_NAME
    entrypoint: [ "docker" ]
    command:
      - buildx
      - rm
      - "${PROJECT_NAME}-builder"
