#!/usr/bin/env bash
set -eo pipefail

ensure_no_barking() {
  results=$(grep -n --include '*.go' --exclude .git -r 'fmt.Printf' "$PWD")
  test -z "$results" && exit 0

  >&2 echo "ERROR: Found fmt.Printf barks in the files below; delete them to
continue the push:

$(echo "$results" | sed -E 's/^/- /')"
}

ensure_no_barking
