---
name: Publish Flightera Summarizer
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: extractions/setup-just@v2

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/docker-compose.yaml') }}"

      - name: Cache compiled Go dependencies
        uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}"
          path: |
            ${{ runner.temp }}/.gocache
            ${{ runner.temp }}/.gomod

      - uses: KengoTODA/actions-setup-docker-compose@main
        name: Set up Docker Compose
        with:
          version: '2.27.1'

      - name: Test Flightera Summarizer
        run: just test
        env:
          GOARCH: "amd64"
  e2e:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: extractions/setup-just@v2

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/docker-compose.yaml') }}"

      - name: Cache compiled Go dependencies
        uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}"
          path: |
            ${{ runner.temp }}/.gocache
            ${{ runner.temp }}/.gomod

      - uses: KengoTODA/actions-setup-docker-compose@main
        name: Set up Docker Compose
        with:
          version: '2.27.1'

      - name: Run e2e tests Flightera Summarizer
        run: just e2e
        env:
          GOARCH: "amd64"
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
          GPG_PRIVATE_KEY_B64: "${{ secrets.GPG_PRIVATE_KEY_B64 }}"
  publish:
    needs:
      - test
      - e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: extractions/setup-just@v2

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/docker-compose.yaml') }}"

      - uses: KengoTODA/actions-setup-docker-compose@main
        name: Set up Docker Compose
        with:
          version: '2.27.1'

      - name: Publish Flight Summarizer to GitHub Container Registry
        run: just deploy_to_ghcr
        env:
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
